### ISSUE TITLE
import models does not exist

### ISSUE THREAD

**Issue by hanyaqian** [vardaan123/Corr-seq-labeling#1]
Hi,
   the code of  Corr-seq-labeling is perfect, but when i try to run it in my own machine, there is some error.
file __init_.py contain the code "import models " ,but models does exist. what should i do?

thanks.

**Comment by vardaan123** [comment]
You should set your `PYTHONPATH` environment variable to include the directory in which this code folder is located. e.g. if your path to `__init__.py` was `/home/abc/corr-seq-labeling`, then append `/home/abc/` to PYTHONPATH. The it should work.

**Comment by hanyaqian** [comment]
That works! Thank you again :)
